# Generated by Django 3.2.9 on 2021-12-07 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geoapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipaddress",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="ip_addresses", to="auth.user"
            ),
            preserve_default=False,
        ),
    ]
